let a = new Date()
a.setHours(0,0,0,0)
let b = new Date(a.getFullYear(), a.getMonth(), a.getDate()+1)
// let b = new Date(new Date(a.getTime()+ (24 * 60 * 60 * 1000)).setHours(0,0,0,0))
console.log(a.getDate()+ ' '+a.getHours())
console.log(b.getDate()+' '+b.getHours())